### ISSUE TITLE
Duplicate package names

### ISSUE THREAD

**Issue by astrosaeed** [utexas-bwi/scavenger_hunt_api#3]
I downloaded this repo in the same workspace where other BWI packages exist. When running `catkin build `, I would receive this error:

```
RuntimeError: Multiple packages found with the same name "bwi_scavenger":
- bwi_common/bwi_scavenger
- scavenger_hunt_api/bwi_scavenger
```

**Comment by maxsvetlik** [comment]
Yes this is an unfortunate remnant in `bwi_common` while this scavenger_hunt is being evaluated (by you!). After evaluation, this version of scavenger will be migrated into `bwi_common` and this will no longer be an issue.

The simplest solution is to move or delete the `bwi_common/bwi_scavenger` or add a `CATKIN_IGNORE` file in the `bwi_common/bwi_scavenger` folder.
