### ISSUE TITLE
Creating "No Expiration" hunts

### ISSUE THREAD

**Issue by dekent** [utexas-bwi/scavenger_hunt_api#5]
Hey all,

We're testing out the Scavenger Hunt API at UPenn, and ran into two issues with the API instructions:
1. Using the "No Expiration" option when creating a hunt gives the following error: `SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: 'NULL' for column 'end_date' at row 1`
2. Getting the "Bottle Hunt" as suggested on the API page example causes the `scavenger_hunt_node` to segfault (output below).  It works fine if I create my own hunt.
```
[dekent@seas.upenn.edu//get_hunt] Got response from Scavenger Hunt server. Parsing...
[scavenger_hunt_node-2] process has died [pid 7713, exit code -11, cmd /home/dekent/ROS/freight/devel/lib/scavenger_hunt/scavenger_hunt_node __name:=scavenger_hunt_node __log:=/home/dekent/.ros/log/c379e2a2-ee43-11eb-b6c2-d43d7e467e10/scavenger_hunt_node-2.log].
```

**Comment by maxsvetlik** [comment]
Thank you. I'll be looking into this and may request more information and/or testing on your end once fixes are in place.

**Comment by maxsvetlik** [comment]
for item 2 it seems that `Bottle Hunt` doesn't actually exist as a Hunt in the database. I will update the API example page to reflect an existing Hunt.

**Comment by maxsvetlik** [comment]
1 has been resolved after an update to the backend database logic. Instead of changing the documentation, I just made a `Bottle Hunt` that is valid indefinitely. 

Both issues are resolved from my own testing. @dekent if you want to try running the `Bottle Hunt` or making a no-expiry Hunt for testing on your side to verify, that'd be great.

**Comment by dekent** [comment]
Both work for me, thanks!
